myapp/urls.py
from django.conf import settings
from django.urls import path
from myapp import views
from django.contrib.staticfiles.urls import static

app_name = 'myapp'

urlpatterns = [
    path(r'', views.Index.as_view(), name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:topic_id>/', views.Detail.as_view(), name='detail'),
    path(r'findcourses/', views.findcourses, name='findcourses'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'review/', views.review, name='review'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'myaccount/', views.myaccount, name='myaccount'),
    path(r'register/', views.register, name='register'),
    path(r'myorders/', views.myorders, name='myorder'),
    path(r'forgot_password/', views.forgot_password, name='forgot_password')
]

mysiteF20/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Sum

class Topic(models.Model):
    name = models.CharField(max_length=200)
    length = models.IntegerField(default=12)

    def __str__(self):
        return self.name

class Course(models.Model):
    title = models.CharField(max_length=200)
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('50.0')), MaxValueValidator(Decimal('500.0'))])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    num_reviews = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class Student(User):
    LVL_CHOICES = [
        ('HS', 'High School'),
        ('UG', 'Undergraduate'),
        ('PG', 'Postgraduate'),
        ('ND', 'No Degree'),
    ]

    level = models.CharField(choices=LVL_CHOICES, max_length=2, default='HS')
    address = models.CharField(max_length=300, blank=True)
    province=models.CharField(max_length=2, default='ON')
    registered_courses = models.ManyToManyField(Course, blank=True)
    interested_in = models.ManyToManyField(Topic)
    student_image = models.ImageField(blank=True)

    def __str__(self):
        return self.first_name+" "+self.last_name

class Order(models.Model):
    STATUS_CHOICES = [
        (0,'Cancelled'), (1, 'Confirmed'), (2, 'On Hold'),
    ]

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)
    order_status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.student.first_name + " "+ self.student.last_name

    def total_cost(self):
        return self.courses.aggregate(total=Sum('price'))['total']

    def total_items(self):
        return self.courses.count()


class Review(models.Model):
    reviewer = models.EmailField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField(blank=True)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.reviewer

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from myapp.models import Order, Review, Student


class SearchForm(forms.Form):
    LENGTH_CHOICES = [
        (0, ''),
        (8, '8 Weeks'),
        (10, '10 Weeks'),
        (12, '12 Weeks'),
        (14, '14 Weeks'),
    ]
    name = forms.CharField(max_length=100, required=False, label='Student Name')
    length = forms.TypedChoiceField(choices = LENGTH_CHOICES, coerce=int, empty_value=0, required=False, label='Preferred course duration:')
    max_price = forms.IntegerField(min_value=0 ,label='Maximum Price')


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['courses', 'student', 'order_status']
        widgets = {'courses': forms.CheckboxSelectMultiple(), 'order_type':forms.RadioSelect}
        labels = {'student': u'Student Name', }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'course', 'rating', 'comments']
        widgets = {'course': forms.RadioSelect}
        labels = {'reviewer': u'Please enter a valid email', 'rating': u'Rating: An integer between 1 (worst) and 5 (best)'}

class RegisterForm(UserCreationForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'username', 'email', 'level', 'address', 'province', 'registered_courses', 'interested_in']

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['student_image']
        labels = {'student_image': 'Upload Image'}

class ForgotPasswordForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, label='User Name')

myapp/views.py
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.views import View

from .models import Topic, Course, Student, Order
from .forms import SearchForm, OrderForm, ReviewForm, RegisterForm, ForgotPasswordForm, ImageUploadForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test

class Index(View):
    def get(self, request):
        top_list = Topic.objects.all().order_by('id')[:10]
        return render(request, 'myapp/index.html', {'top_list': top_list, 'last_login': request.session.get('last_login', False)})

def about(request):
    visits=request.COOKIES.get('about_visits')
    if visits:
        visits=int(visits)+1
    else:
        visits=1
    response = render(request, 'myapp/about.html',{'visits': visits})
    response.set_cookie('about_visits', visits, expires=300)
    return response

class Detail(View):
    def get(self, request, topic_id):
        topic=get_object_or_404(Topic,pk=topic_id)
        return render(request, 'myapp/detail.html', {'topic': topic})

def findcourses(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            length = form.cleaned_data['length']
            max_price = form.cleaned_data['max_price']
            courselist = Course.objects.filter(price__lte = max_price)
            if length:
                courselist = courselist.filter(topic__length = length)

            return render(request, 'myapp/results.html', {'courselist':courselist, 'name':name, 'length':length})
        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        return render(request, 'myapp/findcourses.html', {'form':form})


def place_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            courses = form.cleaned_data['courses']
            order = form.save()
            student = order.student
            # courses = order.courses
            status = order.order_status
            order.save()
            if status == 1:
                for c in order.courses.all():
                    student.registered_courses.add(c)
            return render(request, 'myapp/order_response.html', {'courses': courses, 'order':order})
        else:
            return render(request, 'myapp/place_order.html', {'form':form})

    else:
        form = OrderForm()
        return render(request, 'myapp/place_order.html', {'form':form})

def review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            rating = form.cleaned_data['rating']
            if(rating < 1 or rating > 5):
                form.add_error('rating', 'You must enter a rating between 1 and 5!')
                return render(request, 'myapp/review.html', {'form': form})
            review = form.save()
            review.course.num_reviews+=1
            review.course.save()
            return redirect('myapp:index')
        else:
            return render(request, 'myapp/review.html', {'form': form})
    else:
        if (not request.user):
            return render(request, 'myapp/error.html', {'error': 'You must be logged in to submit a review'})
        try:
            user = Student.objects.get(id=request.user.id)
        except Student.DoesNotExist:
            user = None

        if (not user):
            return render(request, 'myapp/error.html', {'error': 'Only students can submit a review'})

        if(user.level=='UG' or user.level=='PG'):
            form = ReviewForm()
            return render(request, 'myapp/review.html', {'form': form})
        return render(request, 'myapp/error.html', {'error': 'Only Undergraduate student or Postgraduate student can submit a review'})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = str(timezone.now().isoformat('T', 'seconds'))
                request.session.set_expiry(3600)
                return HttpResponseRedirect(reverse('myapp:myaccount'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))

@login_required(login_url='/myapp/login')
def myaccount(request):
    if(request.user.is_staff):
        return render(request, 'myapp/myaccount.html', {"is_student": False})
    user = Student.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            user.student_image = form.cleaned_data.get('student_image')
            user.save()
    form = ImageUploadForm()
    return render(request, 'myapp/myaccount.html', {"is_student": True, 'form': form, "name":user, 'student_image': user.student_image, "courses":user.registered_courses.all(), "interested_in": user.interested_in.all()})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            courses = form.cleaned_data['registered_courses']
            topics = form.cleaned_data['interested_in']

            student = form.save(commit=False)
            student.set_password(form.cleaned_data['password1'])

            student.save()
            rg = student.registered_courses
            it = student.interested_in
            for t in topics:
                it.add(t)

            for c in courses:
                rg.add(c)

            form.save()
            return redirect('myapp:login')
        else:
            return render(request, 'myapp/register.html', {'form':form})
    else:
        form = RegisterForm()
        return render(request, 'myapp/register.html', {'form': form})

@login_required
def myorders(request):
    try:
        currentUser = Student.objects.get(id=request.user.id)
    except Student.DoesNotExist:
        currentUser = None

    if currentUser:
        orders = Order.objects.filter(student=currentUser).all()
        if orders:
            coursesInOrder = [o.courses.all() for o in orders]
            odate = orders.values_list('order_date', flat=True)
            status = orders.values_list('order_status', flat=True)

            iterableOrders = zip(coursesInOrder, odate, status)

            return render(request, 'myapp/myorders.html', {'orders':iterableOrders })
        else:
            message = "You don't have any orders!"
            return render(request, 'myapp/myorders.html', {'message':message })
    else:
        message = "You Are Not a Registered Student"
        return render(request, 'myapp/myorders.html', {'message': message })

def forgot_password(request):
    if request.method == "POST":
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            try:
                student = Student.objects.get(username=username)
                new_pwd = student.username + "1234"
                student.set_password(new_pwd)
                student.save()
                send_from = 'ravikanani280@gmail.com'
                sent_to = student.email
                mail_content = "Your new password is: " + new_pwd
                send_mail('New Password', mail_content, send_from, [sent_to], fail_silently=False)

                success_message = "New password sent to your email id."
                return render(request, 'myapp/forgot_password.html', {'form': form, 'success_message': success_message})
            except Student.DoesNotExist:
                form= ForgotPasswordForm()
                error_message = 'Invalid Username, Try Again.'
                return render(request, 'myapp/forgot_password.html', {'form': form, 'error_message': error_message})
    else:
        form = ForgotPasswordForm()
        return render(request, 'myapp/forgot_password.html', {'form': form})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block title %}
    eLearning - APP About page
{% endblock %}

{% block body_block %}
    <p> This is an E-learning Website! Search our Topics to find all available Courses. </p>
    <br>
    <p> You've visited about page {{ visits }} times!</p>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>About E-Learning WebApp!</title>
</head>
<body>
    <p> This is an E-learning Website! Search our Topics to find all available Courses. </p>
    <p><a href="{% url 'myapp:index' %}">Main page</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>

    {% if user.is_authenticated %}
        <div class="container">
             <ul class="nav nav-tabs">
                 <li class="nav-item" id="indexLink">
                     <a href = "{% url 'myapp:index' %}" class="nav-link">Home</a>
                 </li>
                 <li class="nav-item" id="indexLink">
                     <a href = "{% url 'myapp:myaccount' %}" class="nav-link">My Account</a>
                 </li>
                 <li class="nav-item" id="indexLink">
                     <a href = "{% url 'myapp:myorder' %}" class="nav-link">My Orders</a>
                 </li>
                 <li class="nav-item" id="findCourseLink">
                     <a href=" {% url 'myapp:findcourses' %}" class="nav-link">Find Courses</a>
                 </li>
                 <li class="nav-item" id="placeOrderLink">
                     <a href="{% url 'myapp:place_order' %}" class="nav-link">Place Order </a>
                 </li>
                 <li class="nav-item" id="indexLink">
                     <a href = "{% url 'myapp:review' %}" class="nav-link">Add Review</a>
                 </li>
                 <li class="nav-item" id="aboutLink">
                     <a href= "{% url 'myapp:about' %}" class="nav-link">About Us</a>
                 </li>

                 <li class="nav-item">
                     <a href="{% url 'myapp:logout' %}" class="nav-link">Log out</a>
                 </li>

             </ul>
         </div>
        <div>
            <h1>{% block myhdg %}Hello {{ user.first_name }} {% endblock %}</h1>
            {% block body_block %} {% endblock %}
        </div>
    {% else %}
        <div>
            <ul>
                <li class="hbar1"><a href= "{% url 'myapp:register' %}">Register New Student</a></li>
                <li class="hbar1"><a href= "{% url 'myapp:login' %}">Log In</a></li>
            </ul>
        </div>
    {% endif %}
    {% if error %}
    <div class="container-fluid pt-3">
        <div class="alert alert-danger">
            {% block error_message_block %} {% endblock %}
        </div>
     </div>
    {% endif %}
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block title %}
    Detail page
{% endblock %}

{% block body_block %}
    {% if topic %}
        <h2> Topic Name: {{ topic.name }} </h2>
        <p>Length: {{ topic.length }} weeks</p>
        <h4> List of courses: </h4>
        <ol>
            {% for course in topic.courses.all %}
                <li> {{ course.title }} &emsp;&emsp;&emsp;Price: {{ course.price }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There is no topic with given id!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Detail page</title>
</head>
<body>
    {% if topic %}
        <h2> Topic Name: {{ topic.name }} </h2>
        <p>Length: {{ topic.length }} weeks</p>
        <h4> List of courses: </h4>
        <ol>
            {% for course in topic.courses.all %}
                <li> {{ course.title }} &emsp;&emsp;&emsp;Price: {{ course.price }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There is no topic with given id!</strong>
    {% endif %}
    <p><a href="{% url 'myapp:index' %}">Main page</a></p>
</body>
</html>

myapp/templates/myapp/error.html
{% extends 'myapp/base.html' %}
{% block error_message_block %}
    <p><b>{{ error }}</b></p>
{% endblock %}

myapp/templates/myapp/findcourses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:findcourses' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Find Courses" />
    </form>

{% endblock %}

myapp/templates/myapp/forgot_password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forgot Password</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body style="background: lavenderblush">
    <div class="container pt-3">
        {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
        {% if success_message %}
            <div class="alert alert-success">{{ success_message }}</div>
        {% endif %}
        <form action="{% url 'myapp:forgot_password' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit1" value="Reset Password" class="btn btn-primary"/>
        </form>
    </div>

</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    Hello Ravi
{% endblock %}

{% block body_block %}
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top  in top_list %}
                <li> <a href="{% url 'myapp:detail' top.id %}">{{ top.name}}</a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
    {% if last_login %}
        <p>You Last Logged In At: {{ last_login }}</p>
    {% else %}
        <p>Your last login was more than one hour ago!</p>
    {% endif %}
{% endblock %}

myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h2>Welcome to your main account page</h2>
    {% if is_student %}
        {% if student_image %}
            <img src="{{ student_image.url }}" height="100" width="100" alt="{{ student_image.name }}"/>
            <br/>
        {% endif %}
        <form method="post" action="{% url 'myapp:myaccount' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit1" value="Upload Image" class="btn btn-primary"/>
        </form>
        <h3>Student Name: </h3>
        <p>{{ name }}</p>
        <br>
        <h3>You are interested in following topics: </h3>
        {% if interested_in %}
            <ol>
                {% for top  in interested_in %}
                    <li> <a href="{% url 'myapp:detail' top.id %}">{{ top.name}}</a> </li>
                {% endfor %}
            </ol>
        {% else %}
            <strong>There are no available topics!</strong>
        {% endif %}

        <h3>You are registered in following courses:</h3>
        {% if courses %}
            <table>
                <tr>
                    <th>No.</th>
                    <th>Course Name</th>
                    <th>Category</th>
                    <th>Length</th>
                </tr>
                {% for course  in courses %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ course.title }}</td>
                        <td>{{ course.topic.name }}</td>
                        <td>{{ course.topic.length }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <strong>You are not registered in any course!</strong>
        {% endif %}
    {% else %}
        <h4>You are not a registered student!</h4>
    {% endif %}
{% endblock %}

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block title %}
    MyOrder Page
{% endblock %}

{% block body_block %}

    {% if message %}
        <div class="alert alert-info">  {{ message }}   </div>
    {% else %}
        <h4>MyOrder List:</h4>
        <table class="table table-bordered">
            <tr>
                <th>Courses</th>
                <th>Order Status</th>
                <th>Order Date</th>
            </tr>
            {% for course, date, status in orders %}
                <tr>
                    <td><ol>
                        {% for c in course %}
                            <li>{{ c.title }}</li>
                        {% endfor %}
                    </ol></td>
                    <td>{{ status }}</td>
                    <td>{{ date }}</td>
                </tr>
            {% endfor %}
        </table>

    {% endif %}

{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    Hello Ravi
{% endblock %}

{% block body_block %}
    {% if courses %}
        <h2>Order confirmed</h2>
        <br>
        <h3>List of the courses in the order:</h3>
        <table>
            <tr>
                <th>No.</th>
                <th>Course Name</th>
                <th>Category</th>
                <th>Length</th>
{#                <th>Price</th>#}
            </tr>
            {% for course  in courses %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ course.title }}</td>
                    <td>{{ course.topic.name }}</td>
                    <td>{{ course.topic.length }}</td>
{#                    <td>{{ course.price }}</td>#}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:place_order' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Place Order" />
    </form>

{% endblock %}

myapp/templates/myapp/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <title>Register Page</title>
</head>
<body style="background: lavenderblush">
    <div class="container pt-3">
        <form action="{% url 'myapp:register' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit1" value="Register" class="btn btn-primary"/>
        </form>
    </div>

</body>
</html>